name: Tests

on: [ push, pull_request, workflow_dispatch ]

jobs:
  PestTests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2', '8.3' ]

    services:
      mysql:
        image: 'mysql:8.0'
        ports:
          - 3306

    name: 'PHP Tests ${{ matrix.php }}'

    steps:
      - name: Checkout changes
        uses: actions/checkout@v1

      - name: Create MySQL Database
        run: |
          sudo systemctl start mysql
          mysql -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }} -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' --port ${{ env.DB_PORT }}

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, gd, xml, sqlite

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --no-scripts

      - name: Run Pest Test Suite
        run: composer test

    env:
      DB_PORT: 3306
      DB_DATABASE: testbench
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PREFIX: 'ti_'
      IGNITER_LOCATION_MODE: multiple
